### ISSUE TITLE
libspotify/api.h: No such file or directory

### ISSUE THREAD

**Issue by khamaileon** [chalkchisel/heroku-libspotify-buildpack#1]
Hi there,

I'm trying to run pyspotify on Heroku but I'm facing an issue.

libspotify/api.h seems to be missing.

I'm using heroku-libspotify-buildpack with the following configuration:

.buildpacks:
https://github.com/bolster/heroku-libspotify-buildpack.git#1.7
https://github.com/heroku/heroku-buildpack-python.git#v58

heroku logs:

remote: -----> Vendoring libffi library done
remote: -----> Vendoring libspotify library done
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-python.git
remote: =====> Detected Framework: Python
remote: -----> Noticed cffi. Bootstrapping libffi.
remote: -----> Installing dependencies with pip
remote:        Collecting pyspotify==2.0.0b5 (from -r requirements.txt (line 20))
remote:          Downloading pyspotify-2.0.0b5.tar.gz (149kB)
remote:            Complete output from command python setup.py egg_info:
remote:            running egg_info
remote:            creating pip-egg-info/pyspotify.egg-info
remote:            writing requirements to pip-egg-info/pyspotify.egg-info/requires.txt
remote:            writing pip-egg-info/pyspotify.egg-info/PKG-INFO
remote:            writing top-level names to pip-egg-info/pyspotify.egg-info/top_level.txt
remote:            writing dependency_links to pip-egg-info/pyspotify.egg-info/dependency_links.txt
remote:            writing manifest file 'pip-egg-info/pyspotify.egg-info/SOURCES.txt'
remote:            warning: manifest_maker: standard file '-c' not found
remote:  
remote:            running build_ext
remote:            building '_spotify_cffi_a6a10b5fxe6bba91a' extension
remote:            creating /tmp/pip-build-bZI_TA/pyspotify/spotify/__pycache__/spotify
remote:            creating /tmp/pip-build-bZI_TA/pyspotify/spotify/**pycache**/spotify/**pycache**
remote:            gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/app/.heroku/python/include/python2.7 -c spotify/**pycache**/_spotify_cffi_a6a10b5fxe6bba91a.c -o /tmp/pip-build-bZI_TA/pyspotify/spotify/__pycache__/spotify/**pycache**/_spotify_cffi_a6a10b5fxe6bba91a.o
remote:            spotify/__pycache__/_spotify_cffi_a6a10b5fxe6bba91a.c:207:28: fatal error: libspotify/api.h: No such file or directory
remote:             #include "libspotify/api.h"
remote:                                        ^
remote:            compilation terminated.
remote:            Traceback (most recent call last):
remote:              File "<string>", line 20, in <module>
remote:              File "/tmp/pip-build-bZI_TA/pyspotify/setup.py", line 73, in <module>
remote:                'Topic :: Software Development :: Libraries',
remote:              File "/app/.heroku/python/lib/python2.7/distutils/core.py", line 151, in setup
remote:                dist.run_commands()
remote:              File "/app/.heroku/python/lib/python2.7/distutils/dist.py", line 953, in run_commands
remote:                self.run_command(cmd)
remote:     Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bZI_TA/pyspotify
remote:              File "/app/.heroku/python/lib/python2.7/distutils/dist.py", line 972, in run_command
remote:                cmd_obj.run()
remote:              File "<string>", line 15, in replacement_run
remote:              File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 207, in find_sources
remote:              File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 291, in run
remote:              File "build/bdist.linux-x86_64/egg/setuptools/command/egg_info.py", line 320, in add_defaults
remote:              File "build/bdist.linux-x86_64/egg/setuptools/command/sdist.py", line 118, in add_defaults
remote:              File "/app/.heroku/python/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
remote:                cmd_obj.ensure_finalized()
remote:              File "/app/.heroku/python/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
remote:                self.finalize_options()
remote:              File "build/bdist.linux-x86_64/egg/setuptools/command/build_py.py", line 28, in finalize_options
remote:              File "/app/.heroku/python/lib/python2.7/distutils/command/build_py.py", line 46, in finalize_options
remote:                ('force', 'force'))
remote:              File "/app/.heroku/python/lib/python2.7/distutils/cmd.py", line 298, in set_undefined_options
remote:                src_cmd_obj.ensure_finalized()
remote:              File "/app/.heroku/python/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
remote:                self.finalize_options()
remote:              File "/tmp/pip-build-bZI_TA/pyspotify/setup.py", line 25, in finalize_options
remote:                from spotify import ffi
remote:              File "spotify/__init__.py", line 128, in <module>
remote:                ffi, lib = _build_ffi()
remote:              File "spotify/__init__.py", line 120, in _build_ffi
remote:                ext_package='spotify')
remote:              File "/app/.heroku/python/lib/python2.7/site-packages/cffi/api.py", line 367, in verify
remote:                lib = self.verifier.load_library()
remote:              File "/app/.heroku/python/lib/python2.7/site-packages/cffi/verifier.py", line 96, in load_library
remote:                self._compile_module()
remote:              File "/app/.heroku/python/lib/python2.7/site-packages/cffi/verifier.py", line 192, in _compile_module
remote:                outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
remote:              File "/app/.heroku/python/lib/python2.7/site-packages/cffi/ffiplatform.py", line 28, in compile
remote:                outputfilename = _build(tmpdir, ext)
remote:              File "/app/.heroku/python/lib/python2.7/site-packages/cffi/ffiplatform.py", line 54, in _build
remote:                raise VerificationError('%s: %s' % (e.__class__.**name**, e))
remote:            cffi.ffiplatform.VerificationError: CompileError: command 'gcc' failed with exit status 1
remote:  
remote:            ----------------------------------------
remote: 
remote:  !     Push rejected, failed to compile Multipack app

**Comment by antonagestam** [comment]
@khamaileon Did you find a solution this problem? I'm running into the same error message!

**Comment by khamaileon** [comment]
@antonagestam Unfortunately no and since Libspotify is deprecated, I encourage you to use the Web API instead (via spotipy or direct calls).
